apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  labels:
{{ include "flink.labels" . | indent 4 }}
    component: taskmanager
spec:
  type: {{ .Values.taskmanager.service.type }}
  ports:
    {{- range $name, $port := .Values.taskmanager.ports }}
    - port: {{ $port }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "flink.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: taskmanager
